---
name: SDR Meter Reader
version: 0.8.30
slug: sdrmr
description: RF to Home Assistant REST API Bridge based on RTL_SDR/RTL_433 for RTL2832U based DVB-T USB tuners
startup: application
boot: auto
homeassistant_api: True
auth_api: True
init: false
map: 
  - config:rw 
  - ssl
  
url: https://https://github.com/pasyn/ha-addons/tree/main/SDRMR
usb: true
host_network: False
#ports:
#  1234/tcp: 1234
#ports_description:
#  1234/tcp: RTL_TCP port
arch: 
  - aarch64
  - amd64
  - armv7
  - i386
  
options:
  debug: False
#  open_external_port: False
  msgType: scm
  ids: ""
  duration: 15
  pause_time: 30
  gas_unit_of_measurement: ft³
  electric_unit_of_measurement: Wh
  water_unit_of_measurement: gal
  scm_plus_gas_divisor: 1
  
schema:
  debug: bool
#  open_external_port: bool
  msgType: list(scm|scm+|scm+,r900|idm|netidm|r900|r900bcd|all)
  ids: str?
  duration: int
  pause_time: int
  gas_unit_of_measurement: list(ft³|m³)
  electric_unit_of_measurement: list(Wh|kWh|MWh)
  water_unit_of_measurement: list(gal|l)
  scm_plus_gas_divisor: int?


